falco:
    falcosidekick:
        enabled: true
        webui:
            enabled: true
        config:
            webhook:
                address: http://webhook-falco-eventsource-svc.argo-events.svc.cluster.local:12000/falco
                customHeaders: Source:falco
            loki:
              hostport: http://loki.cloudconf2022demo:3100
    fakeEventGenerator:
      enabled: false
    driver:
      enabled: true
      kind: ebpf
    collectors:
      enabled: false
    services:
      - name: k8saudit-webhook
        type: NodePort
        ports:
          - port: 9765 # See plugin open_params
            nodePort: 30007
            protocol: TCP
    falco:
      plugins:
        - name: k8saudit
          library_path: libk8saudit.so
          init_config:
            ""
            # maxEventBytes: 1048576
            # sslCertificate: /etc/falco/falco.pem
          open_params: "http://:9765/k8s-audit"
        - name: json
          library_path: libjson.so
          init_config: ""
      load_plugins: [k8saudit, json]
      rulesFile:
        - /etc/falco/falco_rules.yaml
        - /etc/falco/falco_rules.local.yaml
        - /etc/falco/k8s_audit_rules.yaml
        - /etc/falco/rules.d/custom-rules.yaml
    customRules:
      custom-rules.yaml: |-
        - list: website_ips
          items: ['"213.215.222.58"', '"213.215.222.59"']
        
        - rule: Connection to vistatech.it
          desc: Detect attempts to connect to Vista Technology website  
          condition: outbound and fd.sip in (website_ips)
          output: Outbound connection to Vista Technology website https://www.vistatech.it (command=%proc.cmdline connection=%fd.name container_id=%container.id container_name=%container.name %container.info image=%container.image)
          priority: EMERGENCY
          tags: [network]
